# fly.toml app configuration file generated for cafecito-beans-app on 2026-09-08T11:07:26-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cafecito-beans-app'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'
  ignorefile = '.dockerignore'

[env]
  BEANS_API_BASE_URL = 'http://cafecito-beans-api.flycast'
  ESPRESSO_API_BASE_URL = 'http://cafecito-espresso-api.flycast'
  NUXT_PUBLIC_SITE_URL = 'https://cafecito-beans-app.fly.dev'
  NUXT_PUBLIC_GA_MEASUREMENT_ID = 'G-KPG0Y2MBV9'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
  memory = '1gb'
